// Auto-generated RSA-2048 Public Key for offline license verification
// DO NOT MODIFY OR COMMIT PRIVATE KEY TO SOURCE CONTROL

export const PUBLIC_KEY = "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsjHGuo3DWPSutlYyEG5V\nwoC1+pC1Pm/lxqfyexdcQjYD+MNjZTVHvK9l49SHkF1qjrSbBIFs5c9KT3RAPLZo\noBznOovj3w9n9jKwu6NXjusWpfPx02SMEzIzdATavvWVDHCn2wsvRMvqKpoAkAjW\nEkpf/yOJsDA3yb+OOG4qSp/72Eeb6PMuzCLjkRysBk1M6Spjq9a3gr7OGSM39EBR\ndABvGOv//eyH3f1bCRF4gQzgBS3MwoRtSFFU7kPlwTnqHspIqHSwFU602PWujdD0\nOBBUQQnUE4yHOqi6HHd9faNdRsJCHzIi/1b1AuRXSrSyIQDhMKYlDV2Xi6ROmJgA\nLwIDAQAB\n-----END PUBLIC KEY-----\n";
